### PR TITLE
Completely fixed ghosting

### PR DESCRIPTION
**Pull request by 0b101**
I completely fixed the ghosting bug, but I might have introduced a new one.

Below is a picture of the bug.
bug

### CODE REVIEW

**Comment by 0b101** [comment]
Commit “Completely fix ghosting” might accidentally re-add oneLine() which results in a build error. The removal of the second oneLine() should fix the build error.

**Comment by rsammelson** [comment]
@0b101 Is the picture of the new bug, or the one you fixed?

**Comment by 0b101** [comment]
The picture is of the new bug. Anything less than 8 characters will display, anything between 8 and __ are hidden for some reason, and anything __+ will appear on two lines like normal.

**Comment by 0b101** [comment]
I think I fixed the bug.
fixed

I would recommend that you test it a little before creating a pull request on numworks/epsilon. If there are any bugs where something doesn't display or something displays on one line but takes up two lines, try changing the oneLine/singleLine < numbers (checkout my commits for examples). From my tests, I believe that **most, if not all**, calculations display correctly. Most display bugs will happen with things like: tan(80) and sin(96), etc.

For singleLine checking, exact and approximate output < number should be = to the one in calculation_store.h, while the third (exact and approximate) should be < the one in calculation_store.h.

**Comment by rsammelson** [comment]
@0b101 Sorry for the delay, but I finally got a chance to test this code. There is still a bug where some calculations are on one line but take up two, but this is a lot closer, so I am going to go ahead and merge it.

**Pull request merged**
